version: '3'
services:
  app:
    image: auth:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
      - queue
  outh:
    image: outh:latest
    ports:
      - "9080:9080"
  user_service:
    image: user:latest
    ports:
      - "9000:9000"
    depends_on:
      - db
  logger:
    image: logger:latest
    depends_on:
      - queue
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user 
      - MYSQL_PASSWORD=password 
      - MYSQL_DATABASE=microbloggs
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/1.sql
    ports:
      - "3306:3306"
  queue:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
