version: '3'
services:
    app:
      image: connection_hub:latest
      ports:
        - "8000:8000"
      expose:
        - "8000"
      depends_on:
        - db
    db:
      image: mysql:latest
      environment:
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        - MYSQL_USER=user 
        - MYSQL_PASSWORD=password 
        - MYSQL_DATABASE=microbloggs
      volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
      ports:
        - "3306:3306"
      expose:
        - "3306"